-- DB CALENDAR
CREATE DATABASE DB_CALENDAR;
USE DB_CALENDAR;

-- USER_MEMBER
CREATE TABLE USER_MEMBER(
	NO 				INT AUTO_INCREMENT,
    ID 				VARCHAR(20) NOT NULL,
    PW 				VARCHAR(100) NOT NULL,
    MAIL 			VARCHAR(50) NOT NULL,
    PHONE 			VARCHAR(50) NOT NULL,
    AUTHORITY_NO 	INT DEFAULT 1,
    REG_DATE		TIMESTAMP DEFAULT NOW(),
    MOD_DATE 		TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(NO),
    FOREIGN KEY(AUTHORITY_NO) references USER_AUTHORITY(NO)
);

SELECT * FROM USER_MEMBER;
DESC USER_MEMBER;
DROP TABLE USER_MEMBER;

ALTER TABLE USER_MEMBER ADD UNIQUE(ID);

-- USER_AUTHORITY(USER멤버 회원가입이 되어 있을 때 가입자의 권한값을 달리 해주는 테이블임)
CREATE TABLE USER_AUTHORITY(
	NO				INT AUTO_INCREMENT,
    ROLE_NAME 		VARCHAR(20) NOT NULL,
    PRIMARY KEY(NO)
);

INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('PRE_USER');
INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('USER');

SELECT * FROM USER_AUTHORITY;


SELECT * FROM USER_MEMBER M
JOIN USER_AUTHORITY A
ON M.AUTHORITY_NO = A.NO;

DROP TABLE USER_MEMBER;
DROP TABLE USER_AUTHORITY;

SHOW TABLES;
DESC USER_MEMBER;
DESC USER_AUTHORITY;

SELECT * FROM USER_MEMBER;
SELECT * FROM USER_AUTHORITY;

SELECT * FROM ADMIN_AUTHORITY;
DESC ADMIN_AUTHORITY;
DESC ADMIN_MEMBER;
SELECT * FROM ADMIN_MEMBER;

DESC PLAN;
SELECT * FROM PLAN;

--------------------------------

-- DB TODOLIST
CREATE DATABASE DB_TODOLIST;
USE DB_TODOLIST;


-- USER_MEMBER
CREATE TABLE USER_MEMBER(
	NO 				INT AUTO_INCREMENT,
    ID 				VARCHAR(20) UNIQUE NOT NULL,
    PW 				VARCHAR(100) NOT NULL,
    MAIL 			VARCHAR(50) NOT NULL,
    PHONE 			VARCHAR(50) NOT NULL,
    ADDRESS			VARCHAR(255) NOT NULL,
    AUTHORITY_NO 	INT DEFAULT 1,
    REG_DATE		TIMESTAMP DEFAULT NOW(),
    MOD_DATE 		TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(NO),
    FOREIGN KEY(AUTHORITY_NO) references USER_AUTHORITY(NO)
);

SELECT * FROM USER_MEMBER;
DELETE FROM USER_MEMBER WHERE ID = 'chanho';
DESC USER_MEMBER;

-- USER_AUTHORITY
CREATE TABLE USER_AUTHORITY(
	NO				INT AUTO_INCREMENT,
    ROLE_NAME		VARCHAR(20) NOT NULL,
    PRIMARY KEY(NO)
);

INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('PRE_USER');
INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('USER');

SELECT * FROM USER_AUTHORITY;

SELECT * FROM USER_MEMBER M
JOIN USER_AUTHORITY A
ON M.AUTHORITY_NO = A.NO;